import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/thinking/index.ts',
    'src/xml-filter/index.ts',
    'src/tool-calls/index.ts',
    'src/context/index.ts',
    'src/structured/index.ts',
    'src/formatting/index.ts',
    'src/processor/index.ts',
    'src/markdown/index.ts',
    'src/adapters/index.ts',
    'src/adapters/generic.ts',
    'src/adapters/vscode.ts',
    'src/normalizers/index.ts',
    'src/recovery/index.ts',
    'src/sse/index.ts',
    'src/pipeline/index.ts',
    'src/agent/index.ts',
    'src/renderers/index.ts',
    'src/renderers/plain/index.ts',
    'src/renderers/cli/index.ts',
    'src/renderers/streaming-md/index.ts',
    'src/renderers/vscode/index.ts',
    'src/ui/index.ts',
    'src/ag-ui/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  target: 'es2022',
});
