import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'thinking/index': 'src/thinking/index.ts',
    'xml-filter/index': 'src/xml-filter/index.ts',
    'tool-calls/index': 'src/tool-calls/index.ts',
    'context/index': 'src/context/index.ts',
    'structured/index': 'src/structured/index.ts',
    'formatting/index': 'src/formatting/index.ts',
    'processor/index': 'src/processor/index.ts',
    'markdown/index': 'src/markdown/index.ts',
    'adapters/index': 'src/adapters/index.ts',
    'adapters/generic': 'src/adapters/generic.ts',
    'normalizers/index': 'src/normalizers/index.ts',
    'recovery/index': 'src/recovery/index.ts',
    'sse/index': 'src/sse/index.ts',
    'pipeline/index': 'src/pipeline/index.ts',
    'agent/index': 'src/agent/index.ts',
    'renderers/index': 'src/renderers/index.ts',
    'renderers/plain/index': 'src/renderers/plain/index.ts',
    'renderers/cli/index': 'src/renderers/cli/index.ts',
    'renderers/streaming-md/index': 'src/renderers/streaming-md/index.ts',
    'ui/index': 'src/ui/index.ts',
    'ag-ui/index': 'src/ag-ui/index.ts',
    'renderers/ink/index': 'src/renderers/ink/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  target: 'es2022',
});
